// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Fab.ABNFRegexProvider")>]
[<assembly: AssemblyProductAttribute("Fab.ABNFRegexProvider")>]
[<assembly: AssemblyDescriptionAttribute("This library is for the .NET platform implementing Fab.ABNFRegexProvider.")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Fab.ABNFRegexProvider"
    let [<Literal>] AssemblyProduct = "Fab.ABNFRegexProvider"
    let [<Literal>] AssemblyDescription = "This library is for the .NET platform implementing Fab.ABNFRegexProvider."
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
