#r @"C:\Users\Chris\.nuget\packages\fparsec\1.0.3\lib\net40-client\FParsecCS.dll"
#r @"C:\Users\Chris\.nuget\packages\fparsec\1.0.3\lib\net40-client\FParsec.dll"
#r @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.Core.dll"
#r @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.Data.dll"
#r @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.Drawing.dll"
#r @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.IO.Compression.FileSystem.dll"
#r @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.Numerics.dll"
#r @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.Runtime.Serialization.dll"
#r @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.Xml.Linq.dll"
#r @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.Xml.dll"
#r @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.dll"
#load @"c:\Users\Chris\OneDrive\BitBucket\ABNF Parser\ABNFParser\obj\Debug\net461\Parser.AssemblyInfo.fs"
#load @"c:\Users\Chris\OneDrive\BitBucket\ABNF Parser\ABNFParser\Core Rules.fs"
#load @"c:\Users\Chris\OneDrive\BitBucket\ABNF Parser\ABNFParser\Types.fs"
#load @"c:\Users\Chris\OneDrive\BitBucket\ABNF Parser\ABNFParser\Operators.fs"
#load @"c:\Users\Chris\OneDrive\BitBucket\ABNF Parser\ABNFParser\Parser.fs"