// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Fab.ABNFProvider.Runtime")>]
[<assembly: AssemblyProductAttribute("Fab.ABNFProvider")>]
[<assembly: AssemblyDescriptionAttribute("This library is for the .NET platform implementing Fab.ABNFProvider.")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Fab.ABNFProvider.Runtime"
    let [<Literal>] AssemblyProduct = "Fab.ABNFProvider"
    let [<Literal>] AssemblyDescription = "This library is for the .NET platform implementing Fab.ABNFProvider."
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
